#define COLOR_WHITE		  0xFFFFFFFF
#define COLOR_USAGE		  0xF2FF00FF // {F2FF00}
#define COLOR_ERROR       0xbd0000AA // {bd0000}
#define COLOR_SUCCESS     0x04D400AA // {04d400} 
#define COLOR_INFO        0x00a2FFAA  // {00a2ff}  
#define COLOR_WARNING     0xFF8000AA // {ff8000} 
#define COLOR_ADMIN       0xff0011AA // {ff0011}
#define COLOR_SERVER      0xCCCCCCFF // Warna abu-abu elegant penuh (Alpha FF = Pekat/Tidak Transparan)
#define COLOR_RED         0xFF0000FF

//--------[ Color Hex ]--------//
#define CODE_SERVER         "{CCCCCC}"
#define CODE_SUCCESS        "{04D400}"
#define CODE_ERROR          "{bd0000}"
#define CODE_INFO           "{00a2ff}"
#define CODE_WARNING        "{ff8000}"
#define CODE_ADMIN          "{ff0011}"